import sys

# python passing_argv.py --name bes

# print(dir(sys))
# # [
# #   '__displayhook__',
# #   '__doc__',
# #   '__excepthook__',
# #   '__name__',
# #   '__package__',
# #   '__stderr__',
# #   '__stdin__',
# #   '__stdout__',
# #   '_clear_type_cache',
# #   '_current_frames',
# #   '_getframe',
# #   '_mercurial',
# #   'api_version',
# #   'argv',
# #   'builtin_module_names',
# #   'byteorder',
# #   'call_tracing',
# #   'callstats',
# #   'copyright',
# #   'displayhook',
# #   'dont_write_bytecode',
# #   'exc_clear',
# #   'exc_info',
# #   'exc_type',
# #   'excepthook',
# #   'exec_prefix',
# #   'executable',
# #   'exit',
# #   'flags',
# #   'float_info',
# #   'float_repr_style',
# #   'getcheckinterval',
# #   'getdefaultencoding',
# #   'getdlopenflags',
# #   'getfilesystemencoding',
# #   'getprofile',
# #   'getrecursionlimit',
# #   'getrefcount',
# #   'getsizeof',
# #   'gettrace',
# #   'hexversion',
# #   'long_info',
# #   'maxint',
# #   'maxsize',
# #   'maxunicode',
# #   'meta_path',
# #   'modules',
# #   'path',
# #   'path_hooks',
# #   'path_importer_cache',
# #   'platform',
# #   'prefix',
# #   'py3kwarning',
# #   'setcheckinterval',
# #   'setdlopenflags',
# #   'setprofile',
# #   'setrecursionlimit',
# #   'settrace',
# #   'stderr',
# #   'stdin',
# #   'stdout',
# #   'subversion',
# #   'version',
# #   'version_info',
# #   'warnoptions'
# # ]

print('sys.argv',sys.argv)
